config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

resources :skills, only: [ :home, :index, :new, :show, :create, :update, :edit, :destroy] do
  resources :bookings, only: [:new, :create ]
end

resources :users, only: [:show, :edit, :update]
 


  get '/tagged/:tag', to: 'skills#tagged', as: :tagged

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :skills, only: [:index]
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord

  validates :name, :description, :price, :skill_location, presence: true

  geocoded_by :skill_location
  after_validation :geocode, if: :will_save_change_to_skill_location?
  
  validates :description, length: {minimum: 50}
  # validates :tag, inclusion: {in: %w[Driving DIY Coding Chores Teaching Gardening Craftwork Pet\ care Baby\ care Art]}
  belongs_to :user
  has_many :bookings
  has_one_attached :avatar
  has_many_attached :works

  acts_as_taggable_on :tags



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :skills
  has_many :bookings
  has_one_attached :avatar
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base

    rescue_from StandardError,                with: :internal_server_error
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
    private
  
    def not_found(exception)
      render json: { error: exception.message }, status: :not_found
    end
  
    def internal_server_error(exception)
      if Rails.env.development?
        response = { type: exception.class.to_s, error: exception.message }
      else
        response = { error: "Internal Server Error" }
      end
      render json: response, status: :internal_server_error
    end
  end

app/controllers/api/v1/skills_controller.rb
class Api::V1::SkillsController < Api::V1::BaseController
    def index
        @skills = Skill.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

#  before_action :authenticate_user!

    include Pundit
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :location])
  
      # For additional in app/views/devise/registrations/edit.html.erb
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end



  def after_sign_in_path_for(resource)
   skills_path
  end

  def after_sign_up_path_for(resource)
   skills_path
  end

    # after_action :verify_authorized, except: :index, unless: :skip_pundit?
    # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    private

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :set_skill
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(bookings_params)
    @booking.user_id = current_user.id
    @booking.skill = @skill
    if @booking.save
      redirect_to skill_path(@skill), notice: 'Fabulous! Succesfully created booking👏'
    else
      render "new", notice: 'it seems something went wrong, try again'
    end
  end

  private
  def set_skill
    @skill = Skill.find(params[:skill_id])
  end

  def bookings_params
    params.require(:booking).permit(:date, :totalrate, :hoursbooked)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:login, :new]
  def new
  end

  def create
  end

  def login
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  # skip_before_action :authenticate_user!, only: [:index, :show]

  def home
  end

  #GET /skills
  def index

#     @skills = params[:tag] ? Skill.filter(params[:tag]) : @skills = Skill.all

    @skills = Skill.all
    
    @skills = policy_scope(Skill).order(created_at: :desc)



    @markers = @skills.geocoded.map do |skill|
      {
        lat: skill.latitude,
        lng: skill.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { skill: skill }),
        image_url: :CLOUDINARY_URL
      }
    end

    # @skill = Skill.find(params[:tag_id])
  end

  #GET /skills/new
  def new
    @skill = Skill.new
    authorize @skill
  end

  #POST /skills
  def create
    @skill = Skill.new(skill_params)
    @skill.user = current_user
    authorize @skill

    if @skill.save!
puts "skill saved"
      redirect_to user_path(current_user), notice: 'Congrats! Succesfully created skill👏'

    else
      puts @skill.errors.full_messages
      render :new
    end
  end

  #GET /skills/:id
  def show
    @user = @skill.user
  end


  def tagged
    if params[:tag].present?
      @skills = Skill.tagged_with(params[:tag])
    else
      @skills = Skill.all
    end
  end
  private

  def skills_params
    params.require(:skill).permit(:tag)
  end

  #GET /skills/:id/edit
  def edit
  end

  #PATCH,PUT  /skills/:id
  def update
    if @skill.update(skill_params)
      redirect_to @skill, notice: 'Successfully updated'
    else
      render :edit
    end
  end

  #DELETE /skills/:id
  def destroy
    @skill.destroy
    redirect_to skills_path, notice: 'Successfully deleted'
  end

  private


  def set_skill
    @skill = Skill.find(params[:id])
    authorize @skill
  end

  def skill_params
    params.require(:skill).permit(:name, :description, :price, :skill_location, :tag, :tag_list, :remote)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [ :edit, :update]
  def index
    @users = policy_scope(User).order(create_at: :desc)
  end

  def show
     @user = User.find(params[:id])
     authorize @user
  end

  def create
  end

  #  def after_sign_in_path_for(resource)
  #   redirect_to skills_path
  # end

  def edit
   
    @user.avatar.attach(params[:avatar])
    authorize @user
  end

  def update
    
    @skill = Skill.new

    @user.update(user_params)
    redirect_to user_path(@user)
  end


  private

    def set_user
    @user = current_user
    authorize @user
    end

    def user_params
      params.require(:user).permit(:username, :email, :name, :contact, :location, :reviews, :avatar,)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def tag_list
        %w[Driving DIY Coding Chores Teaching Gardening Craftwork "Pet care" "Baby care" Art]
    end
    


    def loginBar(style)
        if current_user.nil?
          (link_to 'Register', new_user_registration_path, class: style) +
            (link_to 'Login', new_user_session_path, class: style)
        else
          link_to 'logout', destroy_user_session_path, method: :delete, class: style
        end
      end
end

app/views/bookings/new.html.erb
<body>

   <!--  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %> -->

<div class="booking-banner d-flex justify-content-center">
  <div class="booking-form-container">
   <h2>Book the skill you need</h2>
    <p>
      Skill provided by: <%= @skill.user.name%><br>
      Hourly rate for <%= @skill.name %>: <span id="price"><%= @skill.price %></span> RMB
    </p>

<div class = "booking-form d-flex ml-3 mr-2">
    <div class="form-inputs-booking d-flex">
<%= simple_form_for [@skill, @booking] do |f| %>
<%= f.input :date, label:'Booking Date'%>
<%= f.input :hoursbooked ,
      hint: ("The input must be an integer"),
      :input_html => {:id => "hours",:value => "0" },
      label:'Hours of skill needed' %>
<%= f.input :totalrate ,
      label:'Total price(RMB)',
      :input_html => {:id => "rate",:value => "0" }
      %>

     

  <div class="form-actions-booking d-flex justify-content-around">
   <!-- <button type="button" onclick="calculatePrice()">Calculate Price</button> -->
    <%= f.button :submit, "Book"%>
    <%= link_to "Back",skill_path(@skill), class: "btn btn-lg btn-light"  %>

  </div>
    <% end %>
    </div>
</div>

      </div>
    </div>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skillswapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,300&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div style="display: flex;">
    <!-- Left content -->
    <div style="flex: 1.4;">
      <div class="banner">
      <div class="row align-items-center fixed-top;">

        <div class="top-home col-sm-12 align-items-center ml-4 mt-2 ">
          <h1>Explore the skills<br>you need</h1>
        </div>

        <div class="top-home col-sm-12 align-items-center ml-4 mt-2 justify-content-start ">
         <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-light"  %>
         <%= link_to "Log In", new_user_session_path, class: "btn btn-lg btn-light"  %>
        </div>
      </div>
    </div>
  </div>

    <!-- Right content -->
    <div style="flex: 0.6; background-color: white;" class = "left-container">

      <div class="container mt-4 mb-4 ml-3">
        <div class="row align-items-center justify-content-center offset-sm-12">

          <div class="col-sm-12 justify-content-center d-flex">
            <%= link_to "Browse All Skills", skills_path, style: 'margin: 0px !important;', class: "btn btn-lg btn-light" %>
          </div>

          <div class="col-sm-12 mb-2">
            <p>or</p>
          </div>

        <div class= "navigation-bar">
            <div class= "navigation-bar-icons row align-items-center ">

            <%= link_to tagged_path(tag: "Driving"), class: "col-5 mt-2 pt-2 pb-2"   do  %>
               <div>
                  <%= image_tag('steering-wheel.png', height: '45', width: '45') %>
                  <p>Driving</p>
               </div>
            <% end %>

            <%= link_to tagged_path(tag: "DIY"), class: "col-5 mt-2 pt-2 pb-2"  do  %>
              <div >
                <%= image_tag('tools-2.png', height: '45', width: '45') %>
                 <p>DIY</p>
              </div>
            <% end %>

            <%= link_to tagged_path(tag: 'Coding'), class: "col-5 mt-2 pt-2 pb-2"  do  %>
              <div >
                <%= image_tag('rest-api.png', height: '45', width: '45') %>
                 <p>Coding</p>
              </div>
            <% end %>

            <%= link_to tagged_path(tag: "Chores"), class: "col-5 mt-2 pt-2 pb-2" do  %>
               <div>
                   <%= image_tag('dishes.png', height: '45', width: '45') %>
                 <p>Chores </p>
              </div>
            <% end %>

            <%= link_to tagged_path(tag: "Teaching"), class: "col-5 mt-2 pt-2 pb-2"  do  %>
              <div>
                <%= image_tag('e-learning.png', height: '45', width: '45') %>
                 <p>Teaching</p>
              </div>
            <% end %>

            <%= link_to tagged_path(tag: "Gardening"), class: "col-5 mt-2 pt-2 pb-2"  do  %>
                <div>
                   <%= image_tag('flowers-garden.png', height: '45', width: '45') %>
                 <p>Gardening</p>
              </div>
            <% end %>


          <%= link_to tagged_path(tag: "Craftword"), class: "col-5 mt-2 pt-2 pb-2 "  do  %>
              <div>
                <%= image_tag('pencil-ruler.png', height: '45', width: '45') %>
                 <p>Craftwork</p>
              </div>
            <% end %>

            <%= link_to "Pet care", class: "col-5 mt-2 pt-2 pb-2"  do  %>
                <div>
                   <%= image_tag('paw.png', height: '45', width: '45') %>
                 <p>Pet care</p>
              </div>
            <% end %>

             <%= link_to tagged_path(tag: "Baby care"), class: "col-5 mt-2 pt-2 pb-2"  do  %>
              <div>
                <%= image_tag('baby-face.png', height: '45', width: '45') %>
                 <p>Baby care</p>
              </div>
            <% end %>

            <%= link_to tagged_path(tag: "Art"), class: "col-5 mt-2 pt-2 pb-2"  do  %>
                <div>
                   <%= image_tag('art.png', height: '45', width: '45') %>
                 <p>Art</p>
              </div>
            <% end %>


        </div>
        </div>
      </div>
    </div>
</div>
</div>

app/views/shared/_edit_profile.html.erb
<%= form_with(model: Skill.new, local: true) do |f| %>
    <div class="form-inputs" style="margin-top: 25px">
      <div class="row">

          <div class="col-6 a">
            <div>
              <div>
                <%= f.label :name %>
              </div>
              <div>
                <%= f.text_field :name, class:"edit-form"  %>
              </div>
            </div>

            <div>
              <div>
                <%= f.label :description %>
              </div>
              <div>
                <%= f.text_area :description, class:"edit-form"  %>
              </div>
            </div>
          </div>


        <div class="col-6 b">
          <div>
            <div>
              <%= f.label :tag  %>
            </div>
            <div>
              <%= f.select(:tag_list, %w[Driving DIY Coding Chores Teaching Gardening Craftwork Pet\ care Baby\ care Art] )  %>
            </div>
          </div>
          <div>
            <div>
              <%= f.label :skill_location %>
            </div>
            <div>
              <%= f.text_field :skill_location, class:"edit-form"  %>
            </div>
          </div>
          <div>
            <div>
              <%= f.label :price %>
            </div>
            <div>
              <%= f.text_field :price, class:"edit-form"  %>
            </div>
          </div>
          <div>
            <div>
              <%= f.label :photo %>
            </div>
            <div>
              <%= f.file_field :price %>
            </div>
          </div>
        </div>

      </div>

    <div class="form-actions">
      <%= f.submit :submit, :class => "form-button"%>
    <%= link_to "Back", :back, class: "btn btn-lg btn-light"%>
  </div>
    </div>

  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light">
    <%= link_to "skillSWAPPER", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse">
      <nav class= "nav nav-masthead justify-content-between" style="text-decoration: none">

      <% if !current_user.nil? %>
          <%=  link_to "Profile", user_path(current_user), class: "nav-link"  %>
          <% end %>


          <%= link_to "Categories", root_path, class: "nav-link" %>
          <%= loginBar "nav-link" %>
     </nav>
    </div>
  </div>

app/views/shared/_results.html.erb
  <div class="page-wrapper">
    <div class="row">

      <!--Start Column 1: Left for content -->
      <div class="double-column">

        <!--Start White Column -->
        <div class="white-column">
          <div class="first-title">
            <h1>Book your services</h1>
          </div>
          <div class="second-title">
            <h1><%= current_page?( '/skills') ? "All Skills" : @skills.first.tag %></h1>
          </div>
        </div>
        <!--End White Column -->

        <!--Start Cards Display-->
        <div class="cards-display">

          <!--Start one card-->
         <% @skills.limit(10).each do |skill|%>
          <div class="card-product">
            <div>
              <div>
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar-large", alt: "avatar-large" %>
              </div>

              <div class="book-button">
                <%= link_to "View", skill_path(skill) %>
              </div>
            </div>
            <div class="card-product-infos">
              <div class="card-name">
                <h3><%= skill.user.name %></h3>
              </div>

              <div class="card-skill">
                <h2><%= skill.name %></h2>
              </div>

              <div class="card-location">
                <div class="price">
                  <p><%= skill.price %></p>
                </div>
                <div class="location">
                  <p><%= skill.skill_location %></p>
                </div>
              </div>

              <div class="remote">
                <p><%= skill.remote %></p>
              </div>
            </div>

          </div>
          
          <% end %>
          
          <!--End one card-->

 
        </div>
        <!--End Cards Display-->

      </div>
      <!--End Column 1: Left for content -->


      <!--Start Column 2: Right for map-->
      <div class="column">
        <div class="map-column">
          <p>Map coming soon</p>
        </div>
      </div>
      <!--End Column 2: Right for map-->
    </div>
    <!--end of row class-->
  </div> 
  <!--end of page-wrapper class-->

app/views/skills/_info_window.html.erb
<h2><%= skill.name %></h2>
<p><%= skill.skill_location %></p>

app/views/skills/edit.html.erb
<head>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,800;1,800&display=swap" rel="stylesheet">
</head>

<!-- <div class="form_skill <%= yield(:form_skill) %>"> -->

<div class="new-skill-container">
<h1>Edit skill</h1>


<div class="skill-form-container">

  <%= simple_form_for(@skill) do |f| %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :tag, collection: %w[Driving DIY Coding Chores Teaching Gardening Craftwork Pet\ care Baby\ care Art] %>
      <%= f.input :skill_location %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file, input_html: { multiple: true }, class: "input-photo" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => "form-button"%>
    <%= link_to "Back", :back, class: "btn btn-lg btn-light"%>
  </div>
    </div>

  <% end %>
</div></div>


</div>

app/views/skills/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,800;1,800&display=swap" rel="stylesheet">
</head>

<%=render "shared/nav"  %>


<body>

  <div class="page-wrapper">
    <div class="skill-home-page row">

      <!-- Start Column 1: Left for content -->
      <div class="skill-home-page-collumn double-column">

        <!--Start White Column -->
       <div class="white-column">

          <div class= "index-skills-back-button d-flex justify-content-center ">
            <%= link_to "Back",root_path, class: "btn btn-lg btn-light"%>
          </div>
            <h2>Book your services</h2>
        </div>

        <!-- End White Column -->




        <!--Start Cards Display-->
        <div class="cards-display">

          <!--Start one card-->
        <% @skills.last(8).each do |skill|%>
          <div class="one-card">
            <div class="one-card-left">
              <div class="thumbnail">
                <%= image_tag "https://images.unsplash.com/photo-1569913486515-b74bf7751574?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=670&q=80", class: "img", alt: "thumbnail" %>
              </div>

              <div>
                <%= link_to "View", skill_path(skill), class: "skill-home-page-view-button" %>
              </div>
            </div>


            <div class="one-card-content">
              <!-- <div class="one-card-info"> -->
              <h3><%= link_to skill.user.name, user_path(skill.user), style: "color: black" %></h3>

              <h2><%= skill.name %></h2>

              <p><i class="fas fa-coins"></i> <%= skill.price %> RMB/hr</p>

              <p><i class="fas fa-map-marker-alt"></i> <%= skill.skill_location %></p>

            </div>
            <!-- </div> -->

          </div>

          <% end %>

          <!--End one card-->

        </div>
        <!--End Cards Display-->

      </div>
      <!--End Column 1: Left for content -->


      <!--Start Column 2: Right for map-->
      <div class="column">
          <div id="map"
          style="width: 100%; height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
      </div>
      <!--End Column 2: Right for map-->
    </div>
    <!--end of row class-->
  </div>




  <!--end of page-wrapper class-->
</body>




<!--  -->

app/views/skills/new.html.erb
<head>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,800;1,800&display=swap" rel="stylesheet">
</head>

<!-- <div class="form_skill <%= yield(:form_skill) %>"> -->

<div class="new-skill-container">
<h1>Add a new skill</h1>


<div class="skill-form-container">

  <%= simple_form_for(@skill) do |f| %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :tag, collection: %w[Driving DIY Coding Chores Teaching Gardening Craftwork Pet\ care Baby\ care Art] %>
      <%= f.input :skill_location %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file, input_html: { multiple: true }, class: "input-photo" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => "form-button"%>
    <%= link_to "Back", :back, class: "btn btn-lg btn-light"%>
  </div>
    </div>

  <% end %>
</div></div>


</div>

app/views/skills/show.html.erb
<head>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&family=Quicksand:wght@300&display=swap" rel="stylesheet">
</head>
  <!--navbar starts-->
  <%= render "shared/nav" %>



  <!--navbar ends-->

  <!--PAGE HEADING-->
<!--<div class="skils-show-heading">
  <h3>About my service</h3>
</div>-->
  <!--PAGE HEADING-->
<body>

  <div class= "form-actions-back-button">
    <%= link_to "Back to skills list", skills_path, class: "btn btn-lg btn-light"  %>
  </div>

<div class="skills-show-container">



  <!--FIRST SECTION OF PAGE STARTS-->
<div class="first-section">

    <div class="avatar-picture">
     <% if @user.avatar.attached? %>
      <%= cl_image_tag @user.avatar.key, height:300, width:300 %> 
         <%end%>
    </div>

    <div class="user-information">
      <h2>About me</h2>
      <h3 id="info-box-name"><%= @skill.user.name %></h3>
      <p class="info-box-description"><%= @skill.user.background %></p>
      <p id="info-box-location"><%= @skill.user.location %></p>
      <p id="info-box-contact"><%= @skill.user.contact %></p>
    </div>
</div>
  <!--FIRST SECTION OF PAGE ENDS-->




  <!--SECOND SECTION OF PAGE STARTS-->
<div class="second-section">

  <!--services starts-->

  <div class="service-box">


        <div id="service-name">
          <p><%= @skill.name  %></p>
        </div>

        <div id="service-category">
          <p>Category: <%= @skill.tag %></p>
        </div>

        <div id="service-description">
          <p><%= @skill.description %></p>
        </div>

        <div id="service-location">
          <p><%= @skill.user.location %></p>
        </div>

        <div id="service-remote">
          <p><%= @skill.remote %></p>
        </div>

        <div id="service-price">
          <p>Price: <%= @skill.price %> RMB/hr</p>
        </div>
        <div style="margin-bottom: 10px;">
          <%= link_to "Book", new_skill_booking_path(@skill), class:"service-book-button" %>
        </div>
        <div>
          <%= link_to "View all my services", user_path(@skill.user), class:"services-view-button" %>
        </div>
  </div>


    <!--services ends-->


    <!-- showcase-container starts-->
    <div class="showcase-container">
        <h2>Showcased work</h2>
     
        

        <div class="image-holder">
        </div>
      </div>

    </div>

    <!--booking-container ends-->


</div>
  <!--SECOND SECTION OF PAGE ENDS-->
</div>
</body>

app/views/users/show.html.erb
<head>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&family=Quicksand:wght@300&display=swap" rel="stylesheet">
</head>

  <!--navbar starts-->
  <%= render 'shared/nav' %>

  <!--navbar ends-->

<body>

  <div class= "form-actions-back-button d-flex justify-content-between">
    <%= link_to "Back to skills list",skills_path, class: "btn btn-lg btn-light"  %>
    <%= link_to "Edit Profile", edit_user_path(@current_user), class: "btn btn-lg btn-light"  %>
  </div>

<div class="users-show-container">



  <!--FIRST SECTION OF PAGE STARTS-->

<div class="first-section">

    <div class="avatar-picture">
    <% if @user.avatar.attached? %>
      <%= cl_image_tag @user.avatar.key, height:300, width:300 %>
    <%end%>
    </div>

<div class="user-information">
      <h2>About me</h2>
      <h3 id="info-box-name"><%= @user.name %></h3>
      <p class="info-box-description"><%= @user.background %></p>
      <p id="info-box-location"><%= @user.location %></p>
      <p id="info-box-contact"><%= @user.contact %></p>
    </div>
</div>
  <!--FIRST SECTION OF PAGE ENDS-->



  <!--SECOND SECTION OF PAGE STARTS-->

  <div class="second-section">

    <!--services starts-->
    <div class="services-container">
      <h2>My services</h2>

      <% @user.skills.limit(3).each do |skill| %>

        <div class="one-service">
          <div class="one-service-info">
            <div class="one-service-name">
              <p><%= skill.name %></p>
            </div>
            <div class="one-service-category">
              <p><%= skill.tag %></p>
            </div>
          </div>

          <div class="one-service-buttons">
            <div>
              <%= link_to "View", skill_path(skill), class:"one-service-view-button" %>
            </div>

            <div>
              <%= link_to "Book", new_skill_booking_path(skill), class:"one-service-book-button"%>
            </div>
          </div>
        </div>

       <% end %>
    </div>

<!--

-->



    <!--services ends-->

    <!-- booking-container starts-->
    <div class="booking-container">
      <h2>Bookings</h2>
      <div class="booking-header">

        <div class="booking-skill">
          <p>Skill</p>
        </div>

        <div class="booking-name">
          <p>Booked by</p>
        </div>

        <div class="booking-date">
          <p>Date</p>
        </div>
      </div>

      <div class="booking-content">
        <% @user.bookings.limit(1).each do |booking| %>
        <div class="booking-skill">
          <p><%= booking.skill.name %></p>
        </div>

        <div class="booking-name">
          <p><%= booking.skill.user.name %></p>
        </div>

        <div class="booking-date">
          <p><%= booking.date %></p>
        </div>
      </div>
    <% end %>
    </div>

    <!--booking-container ends-->


  </div>

  <!--SECOND SECTION OF PAGE ENDS-->

</div>
</body>